name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential git python3 python3-pip zip openjdk-17-jdk unzip wget curl \
            autoconf automake libtool pkg-config libffi-dev m4 libltdl-dev \
            libssl-dev libsqlite3-dev zlib1g-dev libbz2-dev libncurses5-dev \
            libncursesw5-dev libreadline-dev libgdbm-dev liblzma-dev

          pip install --upgrade pip
          pip install "Cython<3" buildozer virtualenv

      - name: Install Android SDK & NDK
        run: |
          # Install commandline tools
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdtools.zip
          unzip -q cmdtools.zip
          mv cmdline-tools latest

          # Add SDK to PATH (for this step and future steps)
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/31.0.0:$PATH
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/31.0.0" >> $GITHUB_PATH

          # Install SDK packages
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;31.0.0"

          # Download NDK r25b (recommended for p4a)
          cd $ANDROID_HOME
          wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
          unzip -q android-ndk-r25b-linux.zip
          echo "ANDROIDNDK=$ANDROID_HOME/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/android-ndk-r25b" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_HOME/android-ndk-r25b" >> $GITHUB_ENV
          echo "$ANDROID_HOME/android-ndk-r25b" >> $GITHUB_PATH

      - name: Fix sdkmanager path for Buildozer
        run: |
          mkdir -p /home/runner/android-sdk/tools/bin
          ln -sf /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager /home/runner/android-sdk/tools/bin/sdkmanager

      - name: Build APK
        run: |
          buildozer init || true
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
