name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3 python3-pip zip openjdk-17-jdk unzip
          pip install --upgrade pip
          pip install buildozer cython virtualenv

          # Add Android SDK tools to PATH
          echo "/usr/local/lib/android/sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "/usr/local/lib/android/sdk/platform-tools" >> $GITHUB_PATH
          echo "/usr/local/lib/android/sdk/build-tools/31.0.0" >> $GITHUB_PATH

          # Create legacy path for Buildozer compatibility
          mkdir -p /usr/local/lib/android/sdk/tools/bin
          ln -s /usr/local/lib/android/sdk/cmdline-tools/latest/bin/sdkmanager /usr/local/lib/android/sdk/tools/bin/sdkmanager
          ln -s /usr/local/lib/android/sdk/cmdline-tools/latest/bin/avdmanager /usr/local/lib/android/sdk/tools/bin/avdmanager

      - name: Install Android SDK packages
        run: |
          yes | sdkmanager --sdk_root=/usr/local/lib/android/sdk --licenses
          sdkmanager --sdk_root=/usr/local/lib/android/sdk \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;31.0.0"

      - name: Build APK
        run: |
          buildozer init || true
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
